name: Check code
on:
  workflow_call:
    inputs:
      repo-default-branch:
        default: ${{ github.event.repository.default_branch }}
        description: The name of the develop branch
        required: false
        type: string
    secrets:
      github-token:
        required: true
        description: The GitHub token to use for authentication

jobs:
  check-code:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          repository: thedome/reusable-workflows
          path: .github/actions/thedome/reusable-workflows
      - uses: ./.github/actions/thedome/reusable-workflows/check-code-formatting
        with:
          repo-default-branch: ${{ inputs.repo-default-branch }}
          github-token: ${{ secrets.github-token }}
  ci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: thedome/reusable-actions
          path: .github/actions/thedome/reusable-actions
      - uses: thedome/reusable-actions/ci-lint@main
        with:
          repo-default-branch: ${{ inputs.repo-default-branch }}
          github-token: ${{ secrets.github-token }}
